// <auto-generated />
namespace LunchPicker.Infrastructure.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class FixStateMispelling : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(FixStateMispelling));
        
        string IMigrationMetadata.Id
        {
            get { return "201411021516036_FixStateMispelling"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
